package com.fieldforcehub.mobile;
import android.app.*;import android.content.*;import android.media.*;import android.net.Uri;import android.os.*;
public class AlarmRingService extends Service {
 private MediaPlayer player;private AudioFocusRequest focus;
 @Override public IBinder onBind(Intent i){return null;}
 @Override public int onStartCommand(Intent i,int flags,int startId){String title=i==null?"FieldForce alarm":i.getStringExtra("title");NotificationManager nm=getSystemService(NotificationManager.class);NotificationChannel ch=new NotificationChannel("ffh_alarm_v1","FieldForce alarms",NotificationManager.IMPORTANCE_HIGH);ch.setSound(null,null);nm.createNotificationChannel(ch);PendingIntent stop=PendingIntent.getBroadcast(this,0,new Intent(this,AlarmReceiver.class).setAction("ffh.stopAlarm"),PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);PendingIntent open=PendingIntent.getActivity(this,0,new Intent(this,AlarmActivity.class).putExtra("title",title),PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);
 Notification notification=new Notification.Builder(this,"ffh_alarm_v1").setSmallIcon(R.drawable.ic_stat_ffh).setContentTitle(title).setContentText("Alarm ringing · tap STOP to dismiss").setContentIntent(open).setCategory(Notification.CATEGORY_ALARM).setOngoing(true).setColor(0xffff9f43).addAction(new Notification.Action.Builder(null,"STOP",stop).build()).build();startForeground(7102,notification);
 if(player==null)try{AudioAttributes attr=new AudioAttributes.Builder().setUsage(AudioAttributes.USAGE_ALARM).setContentType(AudioAttributes.CONTENT_TYPE_SONIFICATION).build();focus=new AudioFocusRequest.Builder(AudioManager.AUDIOFOCUS_GAIN_TRANSIENT).setAudioAttributes(attr).setOnAudioFocusChangeListener(change->{if(change==AudioManager.AUDIOFOCUS_LOSS)stopSelf();}).build();getSystemService(AudioManager.class).requestAudioFocus(focus);player=new MediaPlayer();player.setAudioAttributes(attr);String fallback="android.resource://"+getPackageName()+"/"+R.raw.ffh_brand;String chosen=getSharedPreferences("ffh_alarm_options",0).getString("sound_uri",fallback);try{player.setDataSource(this,Uri.parse(chosen));player.prepare();}catch(Exception unavailable){player.reset();player.setAudioAttributes(attr);player.setDataSource(this,Uri.parse(fallback));player.prepare();}player.setLooping(true);player.start();}catch(Exception e){stopSelf();}return START_NOT_STICKY;}
 @Override public void onDestroy(){if(player!=null){player.stop();player.release();player=null;}if(focus!=null)getSystemService(AudioManager.class).abandonAudioFocusRequest(focus);stopForeground(STOP_FOREGROUND_REMOVE);super.onDestroy();}
}
