package com.fieldforcehub.mobile;
import android.Manifest;
import android.app.Activity;
import android.content.Intent;
import android.content.pm.PackageManager;
import android.net.Uri;
import android.os.Bundle;
import android.webkit.*;
import androidx.webkit.WebViewCompat;
import androidx.webkit.WebViewFeature;
import com.onesignal.OneSignal;
import com.onesignal.Continue;
import org.json.JSONObject;
import java.util.Set;
import java.util.Arrays;
import java.util.HashSet;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
public class MainActivity extends Activity {
 static final String HOME="https://mehedialimayon-del.github.io/salesman-performance-app/";
 private WebView web;private JSONObject pendingDuty;private final ExecutorService io=Executors.newSingleThreadExecutor();private ValueCallback<Uri[]> fileCallback;private String pendingPage;
 private GeolocationPermissions.Callback locationCallback;private String locationOrigin;
 private boolean trusted(Uri u){return "https".equals(u.getScheme())&&"mehedialimayon-del.github.io".equals(u.getHost())&&u.getPath()!=null&&u.getPath().startsWith("/salesman-performance-app/");}
 @Override public void onCreate(Bundle b){super.onCreate(b);web=new WebView(this);setContentView(web);web.setBackgroundColor(0xff070a0d);WebSettings s=web.getSettings();s.setJavaScriptEnabled(true);s.setUserAgentString(s.getUserAgentString()+" FFHNative/1");s.setDomStorageEnabled(true);s.setAllowFileAccess(false);s.setAllowContentAccess(true);s.setMixedContentMode(WebSettings.MIXED_CONTENT_NEVER_ALLOW);
 if(!WebViewFeature.isFeatureSupported(WebViewFeature.WEB_MESSAGE_LISTENER)){status("Update Android System WebView to enable secure native tracking.");}else WebViewCompat.addWebMessageListener(web,"FFHBridge",new HashSet<>(Arrays.asList("https://mehedialimayon-del.github.io")),(v,m,origin,main,reply)->{if(!main||!trusted(Uri.parse(v.getUrl())))return;try{JSONObject cmd=new JSONObject(m.getData());String a=cmd.getString("action");JSONObject p=new JSONObject(cmd.optString("payload","{}"));runOnUiThread(()->handle(a,p));}catch(Exception ignored){status("Invalid native request");}});
 web.setWebViewClient(new WebViewClient(){@Override public boolean shouldOverrideUrlLoading(WebView v,WebResourceRequest req){Uri u=req.getUrl();if(trusted(u))return false;if("https".equals(u.getScheme()))startActivity(new Intent(Intent.ACTION_VIEW,u));return true;}@Override public void onPageFinished(WebView v,String url){if(!trusted(Uri.parse(url)))return;String js="window.FieldForceNative={bindIdentity:p=>FFHBridge.postMessage(JSON.stringify({action:'bind',payload:p})),startDuty:p=>FFHBridge.postMessage(JSON.stringify({action:'start',payload:p})),openLocationSettings:()=>FFHBridge.postMessage(JSON.stringify({action:'locationSettings'})),stopDuty:()=>FFHBridge.postMessage(JSON.stringify({action:'stop'})),logout:()=>FFHBridge.postMessage(JSON.stringify({action:'logout'})),exit:()=>FFHBridge.postMessage(JSON.stringify({action:'exit'}))};window.FFH_ONESIGNAL_READY=true;window.FFH_ONESIGNAL_SYNC=async()=>{};window.FFH_ONESIGNAL_ASK_PERMISSION=()=>new Promise(resolve=>{window.ffhNativePermissionResolve=resolve;FFHBridge.postMessage(JSON.stringify({action:'push'}));});window.FFH_ONESIGNAL_STATUS=()=>window.ffhNativePushStatus||{};if(window.FFH_DUTY_NATIVE_READY)window.FFH_DUTY_NATIVE_READY();";web.evaluateJavascript(js,null);pushStatus();if(pendingPage!=null){openPage(pendingPage);pendingPage=null;}}});
 web.setDownloadListener((url,ua,disposition,mime,size)->{if(url.startsWith("https://"))startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(url)));else status("This download needs a browser. Open FieldForce in Chrome for this export.");});
 web.setWebChromeClient(new WebChromeClient(){@Override public void onGeolocationPermissionsShowPrompt(String origin,GeolocationPermissions.Callback cb){if(!("https".equals(Uri.parse(origin).getScheme())&&"mehedialimayon-del.github.io".equals(Uri.parse(origin).getHost()))){cb.invoke(origin,false,false);return;}if(checkSelfPermission(Manifest.permission.ACCESS_FINE_LOCATION)==PackageManager.PERMISSION_GRANTED)cb.invoke(origin,true,true);else{locationCallback=cb;locationOrigin=origin;requestPermissions(new String[]{Manifest.permission.ACCESS_FINE_LOCATION,Manifest.permission.ACCESS_COARSE_LOCATION},102);status("Allow precise location to finish phone setup.");}}@Override public boolean onShowFileChooser(WebView v,ValueCallback<Uri[]> cb,FileChooserParams params){if(fileCallback!=null)fileCallback.onReceiveValue(null);fileCallback=cb;Intent i=params.createIntent();startActivityForResult(Intent.createChooser(i,"Attendance photo"),201);return true;}});
 pendingPage=getIntent().getStringExtra("ffh_page");web.loadUrl(HOME);
 }
 private void handle(String action,JSONObject p){try{switch(action){case "bind":io.execute(()->{try{String token=p.getString("access_token");JSONObject auth=new JSONObject(DutyApi.http("/auth/v1/user",token,null));org.json.JSONArray rows=new org.json.JSONArray(DutyApi.http("/rest/v1/ffh_profiles?select=staff_id,active,login_approved&auth_user_id=eq."+auth.getString("id"),token,null));if(rows.length()!=1||!rows.getJSONObject(0).getBoolean("active")||!rows.getJSONObject(0).getBoolean("login_approved"))throw new Exception("Login not approved");String id=rows.getJSONObject(0).getString("staff_id");SecureStore.merge(this,p);SecureStore.merge(this,new JSONObject().put("staff_id",id));OneSignal.login(id);runOnUiThread(()->{pushStatus();web.evaluateJavascript("if(window.ffhNativePermissionResolve){window.ffhNativePermissionResolve();window.ffhNativePermissionResolve=null;}",null);});}catch(Exception e){status("Native push identity not bound. Sign in again.");}});break;
 case "start":pendingDuty=p;if(checkSelfPermission(Manifest.permission.ACCESS_FINE_LOCATION)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{Manifest.permission.ACCESS_FINE_LOCATION,Manifest.permission.ACCESS_COARSE_LOCATION},101);return;}startPending();break;
 case "locationSettings":startActivity(new Intent(android.provider.Settings.ACTION_LOCATION_SOURCE_SETTINGS));break;
 case "exit":finish();break;
 case "stop":stopService(new Intent(this,DutyLocationService.class));status("Duty location tracking stopped.");break;
 case "logout":stopService(new Intent(this,DutyLocationService.class));SecureStore.clear(this);OneSignal.logout();break;
 case "push":OneSignal.getNotifications().requestPermission(true,Continue.with(r->{runOnUiThread(()->{pushStatus();web.evaluateJavascript("if(window.ffhNativePermissionResolve){window.ffhNativePermissionResolve();window.ffhNativePermissionResolve=null;}",null);});}));break;
 default:status("Unsupported native action");}}catch(Exception e){status("Native operation failed. Retry from Attendance.");}}
 private void startPending(){final JSONObject p=pendingDuty;pendingDuty=null;if(p==null)return;io.execute(()->{try{JSONObject previous=SecureStore.read(this);if(!p.optString("attendance_id").equals(previous.optString("attendance_id")))p.put("queue",new org.json.JSONArray());SecureStore.merge(this,p);JSONObject state=DutyApi.rpc(this,"state",new JSONObject());JSONObject a=state.optJSONObject("attendance");if(a==null||!a.getString("id").equals(p.getString("attendance_id"))||!a.isNull("check_out"))throw new Exception("Inactive duty");SecureStore.merge(this,new JSONObject().put("shift_end",a.getString("shift_end")));runOnUiThread(()->{startForegroundService(new Intent(this,DutyLocationService.class));status("Duty GPS tracking started. The phone shows its tracking notification.");});}catch(Exception e){status("Duty tracking could not start. Check attendance, precise location and internet.");}});}
 private boolean locationEnabled(){android.location.LocationManager lm=(android.location.LocationManager)getSystemService(LOCATION_SERVICE);return lm.isProviderEnabled(android.location.LocationManager.GPS_PROVIDER)||lm.isProviderEnabled(android.location.LocationManager.NETWORK_PROVIDER);}
 @Override public void onResume(){super.onResume();if(web!=null)pushStatus();}
 private void pushStatus(){try{JSONObject p=new JSONObject().put("externalId",SecureStore.read(this).optString("staff_id","")).put("locationPermission",checkSelfPermission(Manifest.permission.ACCESS_FINE_LOCATION)==PackageManager.PERMISSION_GRANTED).put("locationEnabled",locationEnabled()).put("permission",OneSignal.getNotifications().getPermission()?"granted":"default").put("subscriptionId",OneSignal.getUser().getPushSubscription().getId()).put("optedIn",OneSignal.getUser().getPushSubscription().getOptedIn());web.evaluateJavascript("window.ffhNativePushStatus="+p+";window.dispatchEvent(new Event('ffh-native-permissions'));",null);}catch(Exception ignored){}}
 private void status(String msg){runOnUiThread(()->{if(web!=null)web.evaluateJavascript("window.dispatchEvent(new CustomEvent('ffh-native-status',{detail:{message:"+JSONObject.quote(msg)+"}}));",null);});}
 private void openPage(String page){if(new HashSet<>(Arrays.asList("communication","tracking","tasks","notifications","attendance","briefings","zero","cpo")).contains(page))web.evaluateJavascript("window.FFH_NATIVE_OPEN&&window.FFH_NATIVE_OPEN("+JSONObject.quote(page)+");",null);}
 @Override public void onNewIntent(Intent i){super.onNewIntent(i);setIntent(i);String p=i.getStringExtra("ffh_page");if(p!=null)openPage(p);else if(i.getData()!=null&&trusted(i.getData())){String target=i.getData().getQueryParameter("ffh_page");if(target!=null)openPage(target);}}
 @Override public void onRequestPermissionsResult(int request,String[] names,int[] results){super.onRequestPermissionsResult(request,names,results);if(request==102&&locationCallback!=null){locationCallback.invoke(locationOrigin,checkSelfPermission(Manifest.permission.ACCESS_FINE_LOCATION)==PackageManager.PERMISSION_GRANTED,true);locationCallback=null;pushStatus();}if(request==101){if(checkSelfPermission(Manifest.permission.ACCESS_FINE_LOCATION)==PackageManager.PERMISSION_GRANTED)startPending();else{pendingDuty=null;status("Precise location permission is required; tracking is not running.");}}}
 @Override protected void onActivityResult(int r,int c,Intent data){super.onActivityResult(r,c,data);if(r==201&&fileCallback!=null){fileCallback.onReceiveValue(c==RESULT_OK&&data!=null?new Uri[]{data.getData()}:null);fileCallback=null;}}
 @Override public void onBackPressed(){web.evaluateJavascript("history.back()",null);}
 @Override protected void onDestroy(){if(fileCallback!=null)fileCallback.onReceiveValue(null);web.destroy();io.shutdown();super.onDestroy();}
}
