package com.fieldforcehub.mobile;
import android.Manifest;
import android.app.Activity;
import android.content.Intent;
import android.content.pm.PackageManager;
import android.net.Uri;
import android.os.Bundle;
import android.webkit.*;
import androidx.webkit.WebViewCompat;
import androidx.webkit.WebViewFeature;
import com.onesignal.OneSignal;
import com.onesignal.Continue;
import org.json.JSONObject;
import java.util.Set;
import java.util.Arrays;
import java.util.HashSet;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
public class MainActivity extends Activity {
 static final String HOME="https://mehedialimayon-del.github.io/salesman-performance-app/";
 private WebView web;private JSONObject pendingDuty;private final ExecutorService io=Executors.newSingleThreadExecutor();private ValueCallback<Uri[]> fileCallback;private String pendingPage;
 private GeolocationPermissions.Callback locationCallback;private String locationOrigin;private PermissionRequest audioRequest;private byte[] pendingExport;private String exportRequest,voiceRequest;private String voiceLanguage="bn-BD";private VoiceSession voiceSession;
 private boolean trusted(Uri u){return "https".equals(u.getScheme())&&"mehedialimayon-del.github.io".equals(u.getHost())&&u.getPath()!=null&&u.getPath().startsWith("/salesman-performance-app/");}
 @Override public void onCreate(Bundle b){super.onCreate(b);web=new WebView(this);setContentView(web);web.setBackgroundColor(0xff070a0d);WebSettings s=web.getSettings();s.setJavaScriptEnabled(true);s.setUserAgentString(s.getUserAgentString()+" FFHNative/1");s.setDomStorageEnabled(true);s.setAllowFileAccess(false);s.setAllowContentAccess(true);s.setMixedContentMode(WebSettings.MIXED_CONTENT_NEVER_ALLOW);
 if(!WebViewFeature.isFeatureSupported(WebViewFeature.WEB_MESSAGE_LISTENER)){status("Update Android System WebView to enable secure native tracking.");}else WebViewCompat.addWebMessageListener(web,"FFHBridge",new HashSet<>(Arrays.asList("https://mehedialimayon-del.github.io")),(v,m,origin,main,reply)->{if(!main||!trusted(Uri.parse(v.getUrl())))return;try{JSONObject cmd=new JSONObject(m.getData());String a=cmd.getString("action");JSONObject p=new JSONObject(cmd.optString("payload","{}"));runOnUiThread(()->handle(a,p));}catch(Exception ignored){status("Invalid native request");}});
 web.setWebViewClient(new WebViewClient(){@Override public boolean shouldOverrideUrlLoading(WebView v,WebResourceRequest req){Uri u=req.getUrl();if(trusted(u))return false;if("https".equals(u.getScheme()))startActivity(new Intent(Intent.ACTION_VIEW,u));return true;}@Override public void onPageFinished(WebView v,String url){if(!trusted(Uri.parse(url)))return;String js="window.ffhNativeRequests=window.ffhNativeRequests||{};window.ffhNativeReply=(id,result)=>{const entry=window.ffhNativeRequests[id];if(entry){delete window.ffhNativeRequests[id];result.error?entry.reject(new Error(result.error)):entry.resolve(result);}};window.ffhNativeCall=(action,p={})=>new Promise((resolve,reject)=>{p=typeof p==='string'?JSON.parse(p):p;p.request_id=crypto.randomUUID();window.ffhNativeRequests[p.request_id]={resolve,reject};FFHBridge.postMessage(JSON.stringify({action,payload:JSON.stringify(p)}));});window.FieldForceNative={saveFile:p=>window.ffhNativeCall('saveFile',p),voice:p=>window.ffhNativeCall('voice',p),stopVoice:()=>window.ffhNativeCall('stopVoice'),soundSettings:()=>window.ffhNativeCall('soundSettings'),alarmState:()=>window.ffhNativeCall('alarmState'),saveAlarm:p=>window.ffhNativeCall('saveAlarm',p),removeAlarm:p=>window.ffhNativeCall('removeAlarm',p),alarmOptions:p=>window.ffhNativeCall('alarmOptions',p),alarmPermission:()=>window.ffhNativeCall('alarmPermission'),stopAlarm:()=>window.ffhNativeCall('stopAlarm'),bindIdentity:p=>FFHBridge.postMessage(JSON.stringify({action:'bind',payload:p})),startDuty:p=>FFHBridge.postMessage(JSON.stringify({action:'start',payload:p})),openLocationSettings:()=>FFHBridge.postMessage(JSON.stringify({action:'locationSettings'})),stopDuty:()=>FFHBridge.postMessage(JSON.stringify({action:'stop'})),logout:()=>FFHBridge.postMessage(JSON.stringify({action:'logout'})),exit:()=>FFHBridge.postMessage(JSON.stringify({action:'exit'}))};window.FFH_ONESIGNAL_READY=true;window.FFH_ONESIGNAL_SYNC=async()=>{};window.FFH_ONESIGNAL_ASK_PERMISSION=()=>new Promise(resolve=>{window.ffhNativePermissionResolve=resolve;FFHBridge.postMessage(JSON.stringify({action:'push'}));});window.FFH_ONESIGNAL_STATUS=()=>window.ffhNativePushStatus||{};if(window.FFH_DUTY_NATIVE_READY)window.FFH_DUTY_NATIVE_READY();";web.evaluateJavascript(js,null);pushStatus();if(pendingPage!=null){openPage(pendingPage);pendingPage=null;}}});
 web.setDownloadListener((url,ua,disposition,mime,size)->{if(url.startsWith("https://"))startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(url)));else status("This download needs a browser. Open FieldForce in Chrome for this export.");});
 web.setWebChromeClient(new WebChromeClient(){@Override public void onPermissionRequest(PermissionRequest request){runOnUiThread(()->{if(!trusted(Uri.parse(web.getUrl()))||!"https://mehedialimayon-del.github.io".equals(request.getOrigin().toString().replaceAll("/$",""))||!Arrays.asList(request.getResources()).contains(PermissionRequest.RESOURCE_AUDIO_CAPTURE)){request.deny();return;}if(checkSelfPermission(Manifest.permission.RECORD_AUDIO)==PackageManager.PERMISSION_GRANTED)request.grant(new String[]{PermissionRequest.RESOURCE_AUDIO_CAPTURE});else{if(audioRequest!=null)audioRequest.deny();audioRequest=request;requestPermissions(new String[]{Manifest.permission.RECORD_AUDIO},103);}});}@Override public void onPermissionRequestCanceled(PermissionRequest request){if(audioRequest==request)audioRequest=null;}@Override public void onGeolocationPermissionsShowPrompt(String origin,GeolocationPermissions.Callback cb){if(!("https".equals(Uri.parse(origin).getScheme())&&"mehedialimayon-del.github.io".equals(Uri.parse(origin).getHost()))){cb.invoke(origin,false,false);return;}if(checkSelfPermission(Manifest.permission.ACCESS_FINE_LOCATION)==PackageManager.PERMISSION_GRANTED)cb.invoke(origin,true,true);else{locationCallback=cb;locationOrigin=origin;requestPermissions(new String[]{Manifest.permission.ACCESS_FINE_LOCATION,Manifest.permission.ACCESS_COARSE_LOCATION},102);status("Allow precise location to finish phone setup.");}}@Override public boolean onShowFileChooser(WebView v,ValueCallback<Uri[]> cb,FileChooserParams params){if(fileCallback!=null)fileCallback.onReceiveValue(null);fileCallback=cb;Intent i=params.createIntent();startActivityForResult(Intent.createChooser(i,"Choose photo, audio or document"),201);return true;}});
 pendingPage=getIntent().getStringExtra("ffh_page");web.loadUrl(HOME);
 if(!getPreferences(0).getBoolean("notification_setup_requested",false)){getPreferences(0).edit().putBoolean("notification_setup_requested",true).apply();OneSignal.getNotifications().requestPermission(false,Continue.with(r->runOnUiThread(()->pushStatus())));}
 }
 private void handle(String action,JSONObject p){try{switch(action){case "bind":io.execute(()->{try{String token=p.getString("access_token");JSONObject auth=new JSONObject(DutyApi.http("/auth/v1/user",token,null));org.json.JSONArray rows=new org.json.JSONArray(DutyApi.http("/rest/v1/ffh_profiles?select=staff_id,active,login_approved&auth_user_id=eq."+auth.getString("id"),token,null));if(rows.length()!=1||!rows.getJSONObject(0).getBoolean("active")||!rows.getJSONObject(0).getBoolean("login_approved"))throw new Exception("Login not approved");String id=rows.getJSONObject(0).getString("staff_id");if(!SecureStore.read(this).optString("staff_id").equals(id))AlarmStore.clear(this);SecureStore.merge(this,p);SecureStore.merge(this,new JSONObject().put("staff_id",id));getSharedPreferences("ffh_alarm_options",0).edit().putBoolean("remote",true).apply();OneSignal.login(id);if(OneSignal.getNotifications().getPermission())OneSignal.getUser().getPushSubscription().optIn();runOnUiThread(()->{pushStatus();web.evaluateJavascript("if(window.ffhNativePermissionResolve){window.ffhNativePermissionResolve();window.ffhNativePermissionResolve=null;}",null);});}catch(Exception e){status("Native push identity not bound. Sign in again.");}});break;
 case "start":pendingDuty=p;if(checkSelfPermission(Manifest.permission.ACCESS_FINE_LOCATION)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{Manifest.permission.ACCESS_FINE_LOCATION,Manifest.permission.ACCESS_COARSE_LOCATION},101);return;}startPending();break;
 case "saveFile":if(pendingExport!=null){reply(p.optString("request_id"),new JSONObject().put("error","Finish the current file save first"));break;}exportRequest=p.optString("request_id");String encoded=p.getString("base64");if(encoded.length()>28000000){reply(exportRequest,new JSONObject().put("error","Export too large; use Chrome"));exportRequest=null;break;}pendingExport=android.util.Base64.decode(encoded,android.util.Base64.DEFAULT);String filename=p.optString("filename","FieldForce.pdf").replaceAll("[^a-zA-Z0-9._-]","_");Intent create=new Intent(Intent.ACTION_CREATE_DOCUMENT).addCategory(Intent.CATEGORY_OPENABLE).setType(p.optString("mime","application/pdf")).putExtra(Intent.EXTRA_TITLE,filename);startActivityForResult(create,202);break;
 case "voice":if(voiceRequest!=null){reply(p.optString("request_id"),new JSONObject().put("error","Finish current voice input"));break;}voiceRequest=p.optString("request_id");voiceLanguage=p.optString("language","bn-BD");if(checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.RECORD_AUDIO},104);else startVoice();break;
 case "stopVoice":if(voiceSession!=null)voiceSession.stop(null);reply(p.optString("request_id"),new JSONObject().put("stopped",true));break;
 case "soundSettings":startActivity(new Intent(android.provider.Settings.ACTION_CHANNEL_NOTIFICATION_SETTINGS).putExtra(android.provider.Settings.EXTRA_APP_PACKAGE,getPackageName()).putExtra(android.provider.Settings.EXTRA_CHANNEL_ID,"ffh_messages_v2"));reply(p.optString("request_id"),new JSONObject().put("opened",true));break;
 case "alarmState":reply(p.optString("request_id"),new JSONObject().put("exact",AlarmStore.exact(this)).put("remote",getSharedPreferences("ffh_alarm_options",0).getBoolean("remote",true)).put("alarms",AlarmStore.list(this)));break;
 case "saveAlarm":AlarmStore.save(this,p);reply(p.optString("request_id"),new JSONObject().put("saved",true));break;
 case "removeAlarm":AlarmStore.remove(this,p.getString("id"));reply(p.optString("request_id"),new JSONObject().put("saved",true));break;
 case "alarmOptions":getSharedPreferences("ffh_alarm_options",0).edit().putBoolean("remote",p.optBoolean("remote")).apply();if(!p.optBoolean("remote")){org.json.JSONArray all=AlarmStore.list(this);for(int x=0;x<all.length();x++)if(all.getJSONObject(x).optBoolean("remote"))AlarmStore.remove(this,all.getJSONObject(x).getString("id"));}reply(p.optString("request_id"),new JSONObject().put("saved",true));break;
 case "alarmPermission":if(android.os.Build.VERSION.SDK_INT>=31&&!AlarmStore.exact(this))startActivity(new Intent(android.provider.Settings.ACTION_REQUEST_SCHEDULE_EXACT_ALARM,Uri.parse("package:"+getPackageName())));reply(p.optString("request_id"),new JSONObject().put("opened",true));break;
 case "stopAlarm":stopService(new Intent(this,AlarmRingService.class));reply(p.optString("request_id"),new JSONObject().put("stopped",true));break;
 case "locationSettings":startActivity(new Intent(android.provider.Settings.ACTION_LOCATION_SOURCE_SETTINGS));break;
 case "exit":finish();break;
 case "stop":stopService(new Intent(this,DutyLocationService.class));status("Duty location tracking stopped.");break;
 case "logout":AlarmStore.clear(this);stopService(new Intent(this,DutyLocationService.class));SecureStore.clear(this);OneSignal.logout();break;
 case "push":OneSignal.getNotifications().requestPermission(true,Continue.with(r->{runOnUiThread(()->{pushStatus();web.evaluateJavascript("if(window.ffhNativePermissionResolve){window.ffhNativePermissionResolve();window.ffhNativePermissionResolve=null;}",null);});}));break;
 default:status("Unsupported native action");}}catch(Exception e){try{reply(p.optString("request_id"),new JSONObject().put("error",e.getMessage()==null?"Native operation failed":e.getMessage()));}catch(Exception ignored){}status("Native operation failed. Check permissions and retry.");}}
 private void startVoice(){if(voiceRequest==null)return;if(!android.speech.SpeechRecognizer.isRecognitionAvailable(this)){try{reply(voiceRequest,new JSONObject().put("error","Enable phone speech recognition or use the keyboard microphone"));}catch(Exception ignored){}voiceRequest=null;return;}voiceSession=new VoiceSession(this,voiceLanguage,(text,error)->{String id=voiceRequest;voiceRequest=null;voiceSession=null;try{JSONObject result=new JSONObject().put("text",text);if(error!=null&&text.isEmpty())result.put("error",error);if(error!=null)result.put("warning",error);reply(id,result);}catch(Exception ignored){}});voiceSession.start();}
 @Override public void onPause(){if(voiceSession!=null)voiceSession.stop(null);super.onPause();}
 private void reply(String id,JSONObject result){if(id==null||id.isEmpty())return;runOnUiThread(()->{if(web!=null)web.evaluateJavascript("window.ffhNativeReply&&window.ffhNativeReply("+JSONObject.quote(id)+","+result+")",null);});}
 private void startPending(){final JSONObject p=pendingDuty;pendingDuty=null;if(p==null)return;io.execute(()->{try{JSONObject previous=SecureStore.read(this);if(!p.optString("attendance_id").equals(previous.optString("attendance_id")))p.put("queue",new org.json.JSONArray());SecureStore.merge(this,p);JSONObject state=DutyApi.rpc(this,"state",new JSONObject());JSONObject a=state.optJSONObject("attendance");if(a==null||!a.getString("id").equals(p.getString("attendance_id"))||!a.isNull("check_out"))throw new Exception("Inactive duty");SecureStore.merge(this,new JSONObject().put("shift_end",a.getString("shift_end")));runOnUiThread(()->{startForegroundService(new Intent(this,DutyLocationService.class));status("Duty GPS tracking started. The phone shows its tracking notification.");});}catch(Exception e){status("Duty tracking could not start. Check attendance, precise location and internet.");}});}
 private boolean locationEnabled(){android.location.LocationManager lm=(android.location.LocationManager)getSystemService(LOCATION_SERVICE);return lm.isProviderEnabled(android.location.LocationManager.GPS_PROVIDER)||lm.isProviderEnabled(android.location.LocationManager.NETWORK_PROVIDER);}
 @Override public void onResume(){super.onResume();if(web!=null)pushStatus();}
 private void pushStatus(){try{JSONObject p=new JSONObject().put("externalId",SecureStore.read(this).optString("staff_id","")).put("locationPermission",checkSelfPermission(Manifest.permission.ACCESS_FINE_LOCATION)==PackageManager.PERMISSION_GRANTED).put("locationEnabled",locationEnabled()).put("permission",OneSignal.getNotifications().getPermission()?"granted":"default").put("subscriptionId",OneSignal.getUser().getPushSubscription().getId()).put("optedIn",OneSignal.getUser().getPushSubscription().getOptedIn());web.evaluateJavascript("window.ffhNativePushStatus="+p+";window.dispatchEvent(new Event('ffh-native-permissions'));",null);}catch(Exception ignored){}}
 private void status(String msg){runOnUiThread(()->{if(web!=null)web.evaluateJavascript("window.dispatchEvent(new CustomEvent('ffh-native-status',{detail:{message:"+JSONObject.quote(msg)+"}}));",null);});}
 private void openPage(String page){if(new HashSet<>(Arrays.asList("communication","tracking","tasks","notifications","attendance","briefings","meetings","notices","zero","cpo","claims","aiQuestions","aiWork","alarms")).contains(page))web.evaluateJavascript("window.FFH_NATIVE_OPEN&&window.FFH_NATIVE_OPEN("+JSONObject.quote(page)+");",null);}
 @Override public void onNewIntent(Intent i){super.onNewIntent(i);setIntent(i);String p=i.getStringExtra("ffh_page");if(p!=null)openPage(p);else if(i.getData()!=null&&trusted(i.getData())){String target=i.getData().getQueryParameter("ffh_page");if(target!=null)openPage(target);}}
 @Override public void onRequestPermissionsResult(int request,String[] names,int[] results){super.onRequestPermissionsResult(request,names,results);if(request==104){if(checkSelfPermission(Manifest.permission.RECORD_AUDIO)==PackageManager.PERMISSION_GRANTED)startVoice();else{try{reply(voiceRequest,new JSONObject().put("error","Microphone permission denied"));}catch(Exception ignored){}voiceRequest=null;}}if(request==103&&audioRequest!=null){if(checkSelfPermission(Manifest.permission.RECORD_AUDIO)==PackageManager.PERMISSION_GRANTED&&trusted(Uri.parse(web.getUrl())))audioRequest.grant(new String[]{PermissionRequest.RESOURCE_AUDIO_CAPTURE});else audioRequest.deny();audioRequest=null;}if(request==102&&locationCallback!=null){locationCallback.invoke(locationOrigin,checkSelfPermission(Manifest.permission.ACCESS_FINE_LOCATION)==PackageManager.PERMISSION_GRANTED,true);locationCallback=null;pushStatus();}if(request==101){if(checkSelfPermission(Manifest.permission.ACCESS_FINE_LOCATION)==PackageManager.PERMISSION_GRANTED)startPending();else{pendingDuty=null;status("Precise location permission is required; tracking is not running.");}}}
 @Override protected void onActivityResult(int r,int c,Intent data){super.onActivityResult(r,c,data);if(r==303){try{java.util.ArrayList<String> text=data==null?null:data.getStringArrayListExtra(android.speech.RecognizerIntent.EXTRA_RESULTS);reply(voiceRequest,c==RESULT_OK&&text!=null&&!text.isEmpty()?new JSONObject().put("text",text.get(0)):new JSONObject().put("error","Voice input cancelled"));}catch(Exception ignored){}voiceRequest=null;return;}if(r==202){final byte[] bytes=pendingExport;final String requestId=exportRequest;pendingExport=null;exportRequest=null;if(c==RESULT_OK&&data!=null&&data.getData()!=null&&bytes!=null){final Uri destination=data.getData();io.execute(()->{try(java.io.OutputStream out=getContentResolver().openOutputStream(destination)){if(out==null)throw new java.io.IOException("No writable document");out.write(bytes);out.flush();reply(requestId,new JSONObject().put("saved",true));status("File saved successfully.");}catch(Exception e){try{reply(requestId,new JSONObject().put("error","File could not be saved"));}catch(Exception ignored){}status("File could not be saved. Retry the download.");}});}else{try{reply(requestId,new JSONObject().put("error","File save cancelled"));}catch(Exception ignored){}}return;}if(r==201&&fileCallback!=null){fileCallback.onReceiveValue(c==RESULT_OK&&data!=null?new Uri[]{data.getData()}:null);fileCallback=null;}}
 @Override public void onBackPressed(){web.evaluateJavascript("history.back()",null);}
 @Override protected void onDestroy(){if(voiceSession!=null)voiceSession.stop(null);if(audioRequest!=null)audioRequest.deny();pendingExport=null;if(fileCallback!=null)fileCallback.onReceiveValue(null);web.destroy();io.shutdown();super.onDestroy();}
}
