window.FFH_CREATE_ALARMS=function(ctx){'use strict';let syncing=false;
const {FFH_SUPABASE,shell,back,esc,bindBack,q,qa}=ctx;
const rpc=async(action,payload={})=>{const {data,error}=await FFH_SUPABASE.rpc('ffh_alarms',{action,payload});if(error)throw Error(error.message);return data;};
const native=()=>window.FieldForceNative;
const config=a=>({id:a.id,staff_id:a.staff_id,title:a.title,daily:a.daily,enabled:a.enabled,time:(a.time_of_day||'').slice(0,5),at:a.alarm_at?Date.parse(a.alarm_at):0,remote:a.created_by!==a.staff_id});
async function sync(strict=false){if(syncing||!native()?.alarmState||!ctx.user())return;syncing=true;try{const [state,phone]=await Promise.all([rpc('state'),native().alarmState()]);if(!phone.exact){if(strict)throw Error('Enable Alarms & reminders in Android settings');return;}for(const a of state.alarms.filter(a=>a.staff_id===ctx.user().id)){if(!a.enabled)await native().removeAlarm({id:a.id});else if(a.created_by===ctx.user().id||phone.remote)await native().saveAlarm(config(a));else await native().removeAlarm({id:a.id});}}catch(e){console.warn('Alarm sync unavailable',e.message);if(strict)throw e;}finally{syncing=false;}}
window.ffhAlarmsUI=async()=>{try{const state=await rpc('state'),phone=native()?.alarmState?await native().alarmState():null;shell(back('Alarms · Malaysia time')+`<div class="card"><p>Daily or one-time alarms · Malaysia time.</p>${phone?`<p>Exact alarms: ${phone.exact?'ENABLED':'OFF'}</p>${phone.exact?'':'<button class="secondary" id="ffAlarmPermission">ENABLE ALARMS & REMINDERS</button>'}<button class="secondary" id="ffAlarmStop">STOP RINGING ALARM</button>${native()?.chooseAlarmSound?`<p>Alarm sound: ${phone.customSound?'Selected phone sound':'FieldForce music'}</p><button type="button" class="secondary" id="ffChooseAlarmSound">CHOOSE PHONE ALARM SOUND</button><button type="button" class="secondary" id="ffChooseAlarmFile">CHOOSE AUDIO FROM PHONE</button><button type="button" class="secondary" id="ffResetAlarmSound">USE FIELDFORCE MUSIC</button>`:''}`:'<p>Install the updated Android app for alarms while the screen is locked. Browser reminders use notifications.</p>'}</div><div class="card"><form class="form" id="ffAlarmForm"><label>Alarm title<input name="title" required maxlength="160"></label><label>Recipient<select name="staff_id">${state.staff.map(p=>`<option value="${esc(p.id)}">${esc(p.name)} · ${esc(p.id)}</option>`).join('')}</select></label><label><input name="daily" type="checkbox" checked> Repeat every day</label><label>Time (Malaysia)<input name="time" type="time" value="20:25" required></label><label>Date for one-time alarm<input name="date" type="date" value="${new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Kuala_Lumpur'})}"></label><button class="primary">SAVE / ASSIGN ALARM</button><p id="ffAlarmResult" role="status"></p></form></div><div class="card">${state.alarms.map(a=>`<div class="row"><div><b>${esc(a.title)}</b><p>${esc(a.staff_id)} · ${a.daily?'Daily '+esc(a.time_of_day):esc(new Date(a.alarm_at).toLocaleString('en-MY',{timeZone:'Asia/Kuala_Lumpur'}))} · ${a.enabled?'ACTIVE':'CANCELLED'} · by ${esc(a.created_by)}</p></div>${a.enabled&&a.created_by===ctx.user().id?`<button class="secondary ffCancelAlarm" data-id="${a.id}">CANCEL</button>`:''}</div>`).join('')||'<p>No alarms saved.</p>'}</div>`);bindBack();q('#ffAlarmForm').elements.staff_id.value=ctx.user().id;
 if(q('#ffAlarmPermission'))q('#ffAlarmPermission').onclick=()=>native().alarmPermission();if(phone){q('#ffAlarmStop').onclick=()=>native().stopAlarm();}for(const [id,method] of [['ffChooseAlarmSound','chooseAlarmSound'],['ffChooseAlarmFile','chooseAlarmFile'],['ffResetAlarmSound','resetAlarmSound']])if(q('#'+id))q('#'+id).onclick=async()=>{try{await native()[method]();await window.ffhAlarmsUI();}catch(e){alert(e.message)}};
 q('#ffAlarmForm').onsubmit=async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;try{const f=e.target,values=Object.fromEntries(new FormData(f));values.request_id=f.dataset.requestId||(f.dataset.requestId=crypto.randomUUID());values.daily=f.elements.daily.checked;if(!values.daily)values.alarm_at=new Date(values.date+'T'+values.time+':00+08:00').toISOString();if(values.staff_id===ctx.user().id&&phone&&!phone.exact)throw Error('Enable Alarms & reminders, then save again');await rpc('save',values);await sync(true);await window.ffhAlarmsUI();}catch(err){q('#ffAlarmResult').textContent=err.message;b.disabled=false;}};
 qa('.ffCancelAlarm').forEach(b=>b.onclick=async()=>{b.disabled=true;try{await rpc('cancel',{id:b.dataset.id});await sync(true);await window.ffhAlarmsUI();}catch(e){alert(e.message);b.disabled=false;}});
 }catch(e){alert(e.message);}};
window.addEventListener('ffh-native-permissions',()=>sync());window.addEventListener('focus',()=>sync());document.addEventListener('visibilitychange',()=>{if(!document.hidden)sync();});window.FFH_ALARM_SYNC=sync;
return {ui:window.ffhAlarmsUI,sync};
};
