window.FFH_CREATE_BULK_CATALOGUE=ctx=>async function ffhBulkCatalogue(){
 const {isMgr,ffhRefreshCatalogueCloud,ffhCatalogueRows,shell,back,esc,bindBack,q,qa,ffhAssertManagerCloudWrite,ffhUploadPublicFile,ffhSafeName,FFH_SUPABASE,ffhCatalogueLocalRow,ffhSaveCatalogueLocal}=ctx;
 if(!isMgr())return;
 await ffhRefreshCatalogueCloud();ctx.setPage('catalogueBulk');
 const rows=ffhCatalogueRows().map(x=>({...x})),categories=[...new Set(rows.map(x=>x.category))];
 const fields=[['name','Product name'],['itemCode','Item code'],['serialNo','Category serial','number'],['cartonPrice','Carton price RM','number'],['piecePrice','Unit price RM','number'],['pack','Pack'],['ctnFactors','Carton factors'],['ctnBarcode','Carton barcode'],['singlePcsBarcode','Unit barcode'],['comboBarcode','Combo barcode']];
 shell(back('Full Catalogue Edit')+`<form id="ffBulkCatalogueForm"><div class="card" style="position:sticky;top:0;z-index:3"><input id="ffBulkSearch" class="search" placeholder="Find product, code or category"><p id="ffBulkStatus" role="status">${rows.length} products · Edit any rows, then save once.</p><button class="primary" type="submit">SAVE ALL CHANGES</button></div><div id="ffBulkRows">${rows.map((x,i)=>`<section class="card form ffBulkRow" data-index="${i}"><h3>${i+1}. ${esc(x.name)}</h3><div class="ffEditTwo">${fields.map(([k,label,type])=>`<label>${label}<input data-field="${k}" type="${type||'text'}" ${type?'min="0" step="'+(k==='serialNo'?'1':'0.01')+'"':''} value="${esc(x[k]??'')}" ${k==='name'?'required':''}></label>`).join('')}<label>Category<select data-field="category">${categories.map(c=>`<option ${c===x.category?'selected':''}>${esc(c)}</option>`).join('')}</select></label></div>${x.image?`<img src="${esc(x.image)}" loading="lazy" alt="" style="width:70px;height:70px;object-fit:contain">`:''}<label>Product photo · maximum 1.2 MB<input data-field="photo" type="file" accept="image/jpeg,image/png,image/webp"></label><label>Description<textarea data-field="description">${esc(x.description||'')}</textarea></label></section>`).join('')}</div></form>`);bindBack();
 const form=q('#ffBulkCatalogueForm'),dirty=new Map();let saving=false;
 const status=text=>q('#ffBulkStatus').textContent=text;
 form.oninput=e=>{const card=e.target.closest('.ffBulkRow');if(!card||saving)return;const i=+card.dataset.index,x={...rows[i]};card.querySelectorAll('[data-field]').forEach(input=>{const k=input.dataset.field;if(k==='photo'){if(input.files?.[0])x.photoFile=input.files[0];}else x[k]=input.type==='number'?Number(input.value):input.value;});const changed=fields.some(([k])=>String(x[k]??'')!==String(rows[i][k]??''))||x.category!==rows[i].category||x.description!==(rows[i].description||'')||x.photoFile;if(changed)dirty.set(i,x);else dirty.delete(i);status(`${dirty.size} products changed · ${rows.length} total`);};
 q('#ffBulkSearch').oninput=e=>{const term=e.target.value.trim().toLowerCase();qa('.ffBulkRow').forEach(card=>{const x=dirty.get(+card.dataset.index)||rows[+card.dataset.index];card.hidden=![x.name,x.itemCode,x.category].join(' ').toLowerCase().includes(term);});};
 form.onsubmit=async e=>{e.preventDefault();if(saving)return;if(!dirty.size){status('No changes to save.');return;}const button=form.querySelector('[type=submit]');saving=true;button.disabled=true;form.querySelectorAll('.ffBulkRow input,.ffBulkRow select,.ffBulkRow textarea').forEach(el=>el.disabled=true);
 try{await ffhAssertManagerCloudWrite();const changed=[...dirty.values()];for(const x of changed){if(!x.name.trim())throw Error('Product name required');if(!Number.isInteger(x.serialNo)||x.serialNo<0)throw Error('Serial must be a whole number');if(!Number.isFinite(x.cartonPrice)||!Number.isFinite(x.piecePrice)||x.cartonPrice<0||x.piecePrice<0)throw Error('Prices must be zero or greater');if(x.photoFile&&(!['image/jpeg','image/png','image/webp'].includes(x.photoFile.type)||x.photoFile.size>1.2*1024*1024))throw Error('Use JPG, PNG or WebP photos up to 1.2 MB');}
 const used=new Set();for(let i=0;i<rows.length;i++){const x=dirty.get(i)||rows[i];if(!x.serialNo)continue;const key=x.category+'|'+x.serialNo;if(used.has(key)&&changed.some(c=>c.category===x.category&&c.serialNo===x.serialNo&&(c.serialNo!==rows.find(r=>r.id===c.id)?.serialNo||c.category!==rows.find(r=>r.id===c.id)?.category)))throw Error('Duplicate category serial: '+x.category+' #'+x.serialNo);used.add(key);}
 status('Saving '+changed.length+' products…');for(const x of changed)if(x.photoFile)x.image=await ffhUploadPublicFile(x.photoFile,'catalogue/products/'+ffhSafeName(x.itemCode||x.id));
 const payload=changed.map(x=>({id:String(x.cloudId||x.id),name:x.name.trim(),item_code:String(x.itemCode||''),category:x.category,serial_no:x.serialNo,piece_price:x.piecePrice,carton_price:x.cartonPrice,pack:x.pack||'',ctn_factors:String(x.ctnFactors||''),carton_qty:Number(x.ctnFactors)||0,ctn_barcode:x.ctnBarcode||'',single_pcs_barcode:x.singlePcsBarcode||'',combo_barcode:x.comboBarcode||'',description:x.description||'',image_url:x.image||''}));
 const {data,error}=await FFH_SUPABASE.rpc('ffh_catalogue_bulk_save',{products:payload});if(error)throw Error(error.message);if(data?.saved!==changed.length)throw Error('Cloud save verification failed');for(const [i,x] of dirty){delete x.photoFile;Object.assign(ffhCatalogueLocalRow(rows[i]),x,{cloudId:String(x.cloudId||x.id)});rows[i]={...x};}ffhSaveCatalogueLocal();dirty.clear();form.querySelectorAll('[data-field=photo]').forEach(input=>input.value='');status(`${data.saved} products saved · visible to all SRs.`);
 }catch(err){status('Save failed: '+err.message+' · Your edits are still here.');}finally{saving=false;button.disabled=false;form.querySelectorAll('.ffBulkRow input,.ffBulkRow select,.ffBulkRow textarea').forEach(el=>el.disabled=false);}
 };
};
