window.FFH_EXPORT_CLAIM=async function(c,ctx){'use strict';
const load=(src)=>new Promise((ok,no)=>{const el=document.createElement('script');el.src=src;el.onload=ok;el.onerror=()=>no(Error('PDF library could not load'));document.head.append(el)});
if(!window.jspdf)await load('vendor/jspdf.umd.min.js');if(!window.html2canvas)await load('vendor/html2canvas.min.js');if(!window.PDFLib)await load('vendor/pdf-lib.min.js');
const E=ctx.esc,host=document.createElement('div');host.style.cssText='position:fixed;left:-10000px;top:0;width:760px;background:white;color:#14212b;font:16px Arial,sans-serif;z-index:-1';document.body.append(host);const pdf=new window.jspdf.jsPDF({unit:'mm',format:'a4'});let page=0;
async function render(html){const el=document.createElement('section');el.style.cssText='box-sizing:border-box;width:760px;min-height:1074px;padding:38px;background:#fff;color:#14212b;overflow-wrap:anywhere';el.innerHTML=html;host.replaceChildren(el);await document.fonts?.ready;await Promise.all([...el.querySelectorAll('img')].map(img=>img.complete?Promise.resolve():new Promise((ok,no)=>{img.onload=ok;img.onerror=()=>no(Error('Receipt or signature image failed to load'));})));const canvas=await window.html2canvas(el,{scale:1.5,backgroundColor:'#ffffff',logging:false,useCORS:true});const height=canvas.width*297/210;for(let y=0;y<canvas.height;y+=height){const slice=document.createElement('canvas');slice.width=canvas.width;slice.height=Math.min(height,canvas.height-y);slice.getContext('2d').drawImage(canvas,0,y,canvas.width,slice.height,0,0,canvas.width,slice.height);if(page++)pdf.addPage();pdf.addImage(slice.toDataURL('image/png'),'PNG',0,0,210,210*slice.height/slice.width);}}
const header=`<h1 style="margin:0 0 12px;color:#c86d25">FieldForce Hub</h1><h2>${E(c.kind)}</h2><p>${E(c.title)} · ${E(c.claim_month)}</p><p>Staff: ${E(ctx.owner)} (${E(c.owner_staff_id)})<br>Assigned manager: ${E(ctx.reviewer)} (${E(c.reviewer_staff_id)})</p>`;
try{await render(header+`<p style="white-space:pre-wrap">${E(c.details)}</p><table style="border-collapse:collapse;width:100%;color:#14212b"><thead><tr><th style="text-align:left">Date</th><th style="text-align:left">Expense / reason</th><th>RM</th></tr></thead><tbody>${c.lines.map(l=>`<tr><td style="border-bottom:1px solid #ddd;padding:10px">${E(l.expense_date)}</td><td style="border-bottom:1px solid #ddd;padding:10px">${E(l.reason)}${l.excluded?`<br><b>DEDUCTED:</b> ${E(l.deduction_reason)}`:''}</td><td style="border-bottom:1px solid #ddd;padding:10px;text-align:right;${l.excluded?'text-decoration:line-through':''}">${(+l.amount).toFixed(2)}</td></tr>`).join('')}</tbody></table><h2>Total claimed: RM ${ctx.total.toFixed(2)}</h2><p><b>${c.status==='Approved'?'DONE · ':''}${E(c.status)}</b>${c.reviewed_at?' · '+E(new Date(c.reviewed_at).toLocaleString('en-MY')):''}</p>${c.signature_png?`<p>Manager approval signature:</p><img src="${E(c.signature_png)}" style="width:330px;height:auto;max-height:120px">`:''}<p style="font-size:13px">Claim accounting is separate from salary/income.</p>`);
const append=[];if(c.form_path){const form=await fetch(await ctx.signed(c.form_path));if(!form.ok)throw Error('Completed claim form download failed');const file=await form.arrayBuffer();if(c.form_path.toLowerCase().endsWith('.pdf'))append.push(file);else{const encoded=await new Promise((ok,no)=>{const r=new FileReader();r.onload=()=>ok(r.result);r.onerror=no;r.readAsDataURL(new Blob([file],{type:'image/jpeg'}));});await render(`<h2>Completed claim form</h2><img src="${E(encoded)}" style="max-width:680px;max-height:850px;object-fit:contain">`);}}for(const l of c.lines){if(!l.receipt_path)continue;const url=await ctx.signed(l.receipt_path),r=await fetch(url);if(!r.ok)throw Error('Receipt download failed');const bytes=await r.arrayBuffer();if(l.receipt_path.toLowerCase().endsWith('.pdf'))append.push(bytes);else{const blob=new Blob([bytes],{type:l.receipt_path.endsWith('.png')?'image/png':l.receipt_path.endsWith('.webp')?'image/webp':'image/jpeg'});const data=await new Promise((ok,no)=>{const reader=new FileReader();reader.onload=()=>ok(reader.result);reader.onerror=no;reader.readAsDataURL(blob)});await render(`<h2>Receipt · ${E(l.expense_date)} · RM ${(+l.amount).toFixed(2)}</h2><p>${E(l.reason)}${l.excluded?' · DEDUCTED':''}</p><img src="${E(data)}" style="max-width:680px;max-height:850px;object-fit:contain">`);}}
await render(`<h2>Claim review history</h2><p>Claim ID: ${E(c.id)}</p>${c.events.map(e=>`<p style="border-bottom:1px solid #ddd;padding:12px">${E(e.action)} · ${E(e.actor)} · ${E(new Date(e.created_at).toLocaleString('en-MY'))}<br>${E(e.reason)}</p>`).join('')}`);
let bytes=pdf.output('arraybuffer');if(append.length){const merged=await window.PDFLib.PDFDocument.load(bytes);for(const original of append){const doc=await window.PDFLib.PDFDocument.load(original);const pages=await merged.copyPages(doc,doc.getPageIndices());pages.forEach(p=>merged.addPage(p));}bytes=await merged.save();}
await ctx.download(new Blob([bytes],{type:'application/pdf'}),'FFH_'+c.kind.replaceAll(' ','_')+'_'+c.claim_month+'_'+c.id.slice(0,8)+'.pdf');
}finally{host.remove();}
};
