/* Work-hours location and private live communication; authorization is enforced in cloud. */
window.FFH_CREATE_DUTY=function(ctx){
'use strict';
const sb=window.FFH_SUPABASE,core=window.FFH_DUTY_CORE;
let state=null,people=[],channel=null,watch=null,watchSession=null,lastSent=0,map=null,mapLayer=null,peer=null,messages=[],generation=0,poll=null,lastUnread=0;
const $=s=>document.querySelector(s),E=ctx.esc,user=()=>ctx.user(),date=()=>ctx.today(),page=()=>ctx.page(),native=()=>window.FieldForceNative||null;
async function rpc(action,payload={}){const {data,error}=await sb.rpc('ffh_duty',{action,payload});if(error)throw Error(error.message);return data;}
const active=()=>state?.attendance&&!state.attendance.check_out&&Date.parse(state.attendance.shift_end)>Date.now();
const error=err=>{const el=$('#ffDutyStatus')||$('#ffChatStatus');if(el)el.textContent=err.message||String(err);else alert(err.message||String(err));};
async function refresh(){if(!user())return;const next=await rpc('state');const changed=state?.can_track!==next.can_track;state=next;if(!active())stopWeb();if(changed&&page()==='home')ctx.home();if(changed&&page()==='tracking'&&!state.can_track){disposeMap();renderAttendance();}if(page()==='home')updateHome();}
function updateHome(){const b=$('[data-page="tracking"]');if(b)b.hidden=!state?.can_track;const a=$('[data-page="attendance"] small');const chat=$('[data-page="communication"] small');if(chat)chat.textContent=lastUnread?lastUnread+' unread messages':'Private staff messages';if(a)a.textContent=state?.attendance?'Checked in '+new Date(state.attendance.check_in).toLocaleTimeString('en-MY',{hour:'2-digit',minute:'2-digit'}):'Required before work';}
async function init(){await shutdown();await refresh();people=await rpc('directory');channel=sb.channel('ffh-duty-'+user().id)
 .on('postgres_changes',{event:'*',schema:'public',table:'ffh_live_messages'},()=>loadMessages().catch(error))
 .on('postgres_changes',{event:'*',schema:'public',table:'ffh_attendance'},()=>refresh().catch(error))
 .on('postgres_changes',{event:'*',schema:'public',table:'ffh_location_points'},()=>{if(page()==='tracking')loadMap().catch(error)})
 .on('postgres_changes',{event:'*',schema:'public',table:'ffh_duty_settings'},()=>refresh().catch(error))
 .on('postgres_changes',{event:'*',schema:'public',table:'ffh_tracking_grants'},()=>refresh().catch(error)).subscribe();
 poll=setInterval(()=>{if(!user()||document.hidden)return;refresh().catch(console.warn);if(page()==='communication')loadMessages().catch(console.warn);if(page()==='tracking')loadMap().catch(console.warn)},15000);
 // A native identity is validated against Supabase before binding push.
 await syncNativeIdentity();await loadMessages(false);
}
async function syncNativeIdentity(){if(!native()||!user())return;const {data}=await sb.auth.getSession();if(data?.session)native().bindIdentity(JSON.stringify({access_token:data.session.access_token,refresh_token:data.session.refresh_token}));}
async function shutdown(){generation++;stopWeb();if(poll)clearInterval(poll);poll=null;if(channel)await sb.removeChannel(channel);channel=null;disposeMap();state=null;people=[];peer=null;messages=[];lastUnread=0;}
function stopWeb(){if(watch!==null)navigator.geolocation.clearWatch(watch);watch=null;watchSession=null;}
function fix(){return new Promise((resolve,reject)=>{if(!navigator.geolocation)return reject(Error('GPS is unavailable'));navigator.geolocation.getCurrentPosition(p=>{if(p.coords.accuracy>100)return reject(Error('GPS accuracy is too low. Move near an open area and retry.'));resolve({latitude:p.coords.latitude,longitude:p.coords.longitude,accuracy_m:p.coords.accuracy,captured_at:new Date(p.timestamp).toISOString(),speed_mps:p.coords.speed})},e=>reject(Error('Allow precise location and turn GPS on: '+e.message)),{enableHighAccuracy:true,maximumAge:0,timeout:25000});});}
function startWeb(){if(!active()||native())return;if(watchSession===state.attendance.id)return;stopWeb();watchSession=state.attendance.id;const sid=watchSession;watch=navigator.geolocation.watchPosition(async p=>{if(!active()||watchSession!==sid){stopWeb();return;}if(Date.now()-lastSent<15000||p.coords.accuracy>100)return;lastSent=Date.now();try{await rpc('point',{attendance_id:sid,latitude:p.coords.latitude,longitude:p.coords.longitude,accuracy_m:p.coords.accuracy,captured_at:new Date(p.timestamp).toISOString(),speed_mps:p.coords.speed,source:'web'})}catch(e){console.warn('Location upload:',e);}},e=>{console.warn('GPS stopped:',e);if($('#ffDutyStatus'))$('#ffDutyStatus').textContent='Location unavailable: '+e.message},{enableHighAccuracy:true,maximumAge:0,timeout:30000});}
async function startTracking(){if(!active())throw Error('Check in before starting duty tracking');if(native()){const {data,error}=await sb.auth.getSession();if(error||!data?.session)throw Error('Sign in again');native().startDuty(JSON.stringify({attendance_id:state.attendance.id,shift_end:state.attendance.shift_end,access_token:data.session.access_token,refresh_token:data.session.refresh_token}));}else startWeb();}
function gate(target){return !!(user()&&state?.settings?.attendance_required&&!state.attendance&&!['home','attendance','profile','notifications','login'].includes(target));}
function shell(title,html){ctx.setPage(title);ctx.shell(ctx.back(title==='attendance'?'Attendance':title==='tracking'?'SR Tracking':'Live Communication')+html);ctx.bindBack();}
function renderAttendance(){disposeMap();shell('attendance',`<div class="card"><div class="cardTitle">Daily Attendance</div><p>${E(user()?.name||'')} · ${date()} MYT</p><div class="notice">কাজের সময় আপনার GPS লোকেশন, রুট ও আনুমানিক বিরতির সময় অনুমোদিত manager দেখবেন। Checkout বা duty end-এ tracking বন্ধ হবে। Android-এ tracking notification দেখা যাবে।</div>${state?.attendance?`<div class="row"><span>Check-in</span><b>${E(new Date(state.attendance.check_in).toLocaleString('en-MY'))}</b></div><div class="row"><span>Status</span><b>${active()?'ON DUTY':'DUTY ENDED'}</b></div><p class="miniStat">${native()?'Native Android tracking available':'Browser GPS works while the app is active; screen-off history can have gaps.'}</p>${active()?'<button class="primary" id="ffResumeDuty">START / RESUME DUTY TRACKING</button><button class="secondary" id="ffCheckout">CHECK OUT & STOP TRACKING</button>':''}`:`<form class="form" id="ffAttendanceForm"><label>Attendance photo (optional)<input type="file" name="photo" accept="image/*" capture="user"></label><label><input type="checkbox" name="consent" required> আমি কাজের সময় location tracking সম্পর্কে জেনেছি এবং সম্মতি দিচ্ছি।</label><button class="primary" type="submit">CHECK IN & START DUTY</button></form>`}<div id="ffDutyStatus" role="status" class="notice"></div></div><div class="card"><div class="cardTitle">Confirmed Home Area</div><p class="miniStat">শুধু বাসায় থাকাকালে confirm করুন। Attendance-এর জায়গাকে স্বয়ংক্রিয়ভাবে বাসা ধরা হবে না। GPS দিয়ে ঘরের ভিতরে থাকা নিশ্চিত করা যায় না।</p><p>${state?.home?'Confirmed · approximate radius 150 m':'Not confirmed'}</p><button class="secondary" id="ffConfirmHome">CONFIRM CURRENT LOCATION AS HOME</button></div>`);
 if($('#ffAttendanceForm'))$('#ffAttendanceForm').onsubmit=async e=>{e.preventDefault();const button=e.submitter;button.disabled=true;try{if(!e.target.elements.consent.checked)throw Error('Accept the work-hours tracking disclosure');$('#ffDutyStatus').textContent='Getting GPS…';const location=await fix();let photo_path=null;const file=e.target.elements.photo.files[0];if(file){const blob=await compress(file);photo_path=user().id+'/'+crypto.randomUUID()+'.jpg';const {error}=await sb.storage.from('ffh-attendance').upload(photo_path,blob,{contentType:'image/jpeg'});if(error)throw error;}await rpc('checkin',{...location,photo_path,consent_version:'duty-location-v1',tracking_mode:native()?'android':'web'});await refresh();await startTracking();renderAttendance();$('#ffDutyStatus').textContent='Attendance saved. Duty tracking requested.';}catch(err){error(err);button.disabled=false;}};
 if($('#ffResumeDuty'))$('#ffResumeDuty').onclick=()=>startTracking().then(()=>{$('#ffDutyStatus').textContent='Tracking requested; check the phone tracking notification.'}).catch(error);
 if($('#ffCheckout'))$('#ffCheckout').onclick=async()=>{try{await rpc('checkout');stopWeb();native()?.stopDuty();await refresh();renderAttendance();}catch(e){error(e)}};
 $('#ffConfirmHome').onclick=async()=>{if(!confirm('Are you currently at your home? This updates your confirmed home area.'))return;try{const p=await fix();await rpc('home',p);await refresh();renderAttendance();$('#ffDutyStatus').textContent='Home area confirmed.';}catch(e){error(e)}};
}
async function compress(file){const img=await createImageBitmap(file);const scale=Math.min(1,640/Math.max(img.width,img.height)),c=document.createElement('canvas');c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);c.getContext('2d').drawImage(img,0,0,c.width,c.height);img.close();const b=await new Promise(r=>c.toBlob(r,'image/jpeg',.65));if(!b||b.size>250000)throw Error('Photo is too large; choose a smaller image');return b;}
function disposeMap(){generation++;if(map){map.remove();map=null;}mapLayer=null;}
async function renderTracking(){await refresh();if(!state?.can_track)return renderAttendance();disposeMap();shell('tracking',`<div class="card"><div class="cardTitle">SR Tracking · Work Hours</div><p class="miniStat">Location is an estimate. Check last update and accuracy before judging a stop.</p><div class="two"><label>SR<select id="ffTrackStaff"></select></label><label>Date<input id="ffTrackDate" type="date" value="${date()}" max="${date()}"></label></div><div id="ffDutyMap" style="height:380px;border-radius:16px;margin-top:12px"></div><div id="ffDutyStatus" class="notice" role="status"></div><button class="primary" id="ffMapMessage">MESSAGE SELECTED SR</button><button class="secondary" id="ffMapTask">ASSIGN LOCATION TASK</button><div id="ffStopList"></div><div id="ffAttendanceProof"></div></div>${user().id==='M21954'?`<div class="card"><div class="cardTitle">Tracking Viewing Access</div><p class="miniStat">OFF: only your account sees the manager map. SR always sees their own attendance and tracking status.</p><label><input type="checkbox" id="ffShareTracking" ${state.settings.tracking_shared?'checked':''}> Enable assigned viewers</label><form class="form" id="ffTrackingGrant"><label>Viewer<select name="viewer">${people.filter(p=>p.staff_id!==user().id).map(p=>`<option value="${E(p.staff_id)}">${E(p.full_name)} · ${E(p.role)}</option>`).join('')}</select></label><label>SRs this viewer can see<select name="targets" multiple>${people.map(p=>`<option value="${E(p.staff_id)}">${E(p.full_name)}</option>`).join('')}</select></label><button class="secondary">SAVE VIEWING ASSIGNMENT</button><p class="miniStat">Select no SRs to revoke this viewer's access.</p></form></div>`:''}`);
 const {data:rows,error:err}=await sb.from('ffh_attendance').select('staff_id').order('duty_date',{ascending:false}).limit(500);if(err)throw err;
 const visible=new Set((rows||[]).map(r=>r.staff_id));if(user().id==='M21954')people.forEach(p=>visible.add(p.staff_id));else{const {data:g}=await sb.from('ffh_tracking_grants').select('target_staff_ids').eq('viewer_staff_id',user().id).maybeSingle();(g?.target_staff_ids||[]).forEach(id=>visible.add(id));}
 $('#ffTrackStaff').innerHTML=people.filter(p=>visible.has(p.staff_id)).map(p=>`<option value="${E(p.staff_id)}">${E(p.full_name)}</option>`).join('');
 if(!window.L){$('#ffDutyStatus').textContent='Map library could not load. Check your internet connection.';return;}
 map=L.map('ffDutyMap').setView([3.139,101.6869],11);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap contributors',maxZoom:19}).addTo(map);mapLayer=L.layerGroup().addTo(map);setTimeout(()=>map?.invalidateSize(),100);
 $('#ffTrackStaff').onchange=()=>loadMap(true).catch(error);$('#ffTrackDate').onchange=()=>loadMap(true).catch(error);
 $('#ffMapMessage').onclick=()=>{const to=$('#ffTrackStaff').value;const text=prompt('Message this SR about this location:','ভাই, আপনি এই জায়গায় কী কাজ করছেন?');if(text?.trim())send(to,text,{date:$('#ffTrackDate').value,...(currentLocation||{})}).then(()=>{$('#ffDutyStatus').textContent='Message saved and notification queued.'}).catch(error)};
 $('#ffMapTask').onclick=()=>ctx.task($('#ffTrackStaff').value,$('#ffTrackDate').value,currentLocation);
 if($('#ffShareTracking'))$('#ffShareTracking').onchange=async e=>{try{await rpc('access',{shared:e.target.checked});await refresh();$('#ffDutyStatus').textContent='Viewing access updated.';}catch(err){e.target.checked=!e.target.checked;error(err)}};
 if($('#ffTrackingGrant'))$('#ffTrackingGrant').onsubmit=async e=>{e.preventDefault();try{const f=new FormData(e.target);await rpc('access',{shared:$('#ffShareTracking').checked,viewer:f.get('viewer'),targets:f.getAll('targets')});$('#ffDutyStatus').textContent='Viewer assignment saved.';}catch(err){error(err)}};
 await loadMap(true);
}
let mapLoading=false,currentLocation=null;
async function loadMap(fit=false){if(mapLoading||!map||page()!=='tracking')return;mapLoading=true;const gen=generation,staff=$('#ffTrackStaff').value,day=$('#ffTrackDate').value;try{
 const {data:a,error:ae}=await sb.from('ffh_attendance').select('*').eq('staff_id',staff).eq('duty_date',day).maybeSingle();if(ae)throw ae;
 let points=[];if(a){for(let offset=0;offset<10000;offset+=1000){const {data,error}=await sb.from('ffh_location_points').select('latitude,longitude,accuracy_m,speed_mps,captured_at,source').eq('attendance_id',a.id).order('captured_at').range(offset,offset+999);if(error)throw error;points.push(...(data||[]));if(!data||data.length<1000)break;}}
 if(gen!==generation||!map||page()!=='tracking'||$('#ffTrackStaff').value!==staff||$('#ffTrackDate').value!==day)return;
 mapLayer.clearLayers();const stopRows=core.stops(points);for(const line of core.segments(points))L.polyline(line,{color:'#ff7417',weight:3}).addTo(mapLayer);
 for(const stop of stopRows){const marker=L.circleMarker([stop.latitude,stop.longitude],{radius:stop.minutes>=5?7:4,color:'#ffac54',fillOpacity:.9}).addTo(mapLayer);marker.bindTooltip((stop.minutes>=5?stop.minutes+' min · ':'')+new Date(stop.start).toLocaleTimeString('en-MY'),{permanent:stop.minutes>=5,direction:'top'});}
 const last=points.at(-1);currentLocation=last||null;if(last){L.circleMarker([last.latitude,last.longitude],{radius:9,color:'#55cafa',fillOpacity:.7}).bindTooltip('Last recorded location').addTo(mapLayer);L.circle([last.latitude,last.longitude],{radius:last.accuracy_m,color:'#55cafa',weight:1,fillOpacity:.08}).addTo(mapLayer);if(fit)map.setView([last.latitude,last.longitude],15);}
 $('#ffDutyStatus').textContent=!a?'No attendance on this date.':!last?'Attendance saved; no route points received.':`${a.check_out?'Checked out':'Shift ends '+new Date(a.shift_end).toLocaleTimeString('en-MY')} · Last GPS ${new Date(last.captured_at).toLocaleString('en-MY')} · ±${Math.round(last.accuracy_m)} m${Date.now()-Date.parse(last.captured_at)>180000?' · LOCATION STALE / TRACKING GAP':''}`;
 $('#ffStopList').innerHTML='<div class="cardTitle">Estimated Stops</div>'+stopRows.map(s=>`<div class="row"><span>${E(new Date(s.start).toLocaleTimeString('en-MY'))}</span><b>${s.minutes} min</b></div>`).join('');
 const proof=$('#ffAttendanceProof');proof.innerHTML='';if(a?.photo_path){const {data,error}=await sb.storage.from('ffh-attendance').createSignedUrl(a.photo_path,60);if(!error&&gen===generation&&proof.isConnected){const img=document.createElement('img');img.src=data.signedUrl;img.alt='Attendance photo';img.style.cssText='max-width:180px;border-radius:12px';proof.appendChild(img);}}
 }finally{mapLoading=false;}}
async function send(recipient,body,location_context=null){const result=await rpc('message',{id:crypto.randomUUID(),recipient,body,location_context});sb.functions.invoke('ffh-push-dispatch',{body:{}}).catch(console.warn);await loadMessages(false);return result;}
async function loadMessages(announce=true){if(!user())return;const {data,error:err}=await sb.from('ffh_live_messages').select('*').order('created_at',{ascending:false}).limit(500);if(err)throw err;const seen=new Set(messages.map(m=>m.id));const incoming=(data||[]).filter(m=>m.recipient_staff_id===user().id&&!m.read_at&&!seen.has(m.id));messages=(data||[]).reverse();lastUnread=messages.filter(m=>m.recipient_staff_id===user().id&&!m.read_at).length;const badge=$('[data-page="communication"] small');if(badge)badge.textContent=lastUnread?lastUnread+' unread messages':'Private staff messages';if(page()==='communication'){drawContacts();if(peer&&!document.hidden)await drawThread();}else if(announce&&incoming.length)ctx.notice({title:'Live Communication',body:incoming[0].body,target_page:'communication'});}
function renderCommunication(){disposeMap();shell('communication',`<div class="card"><div class="cardTitle">Live Communication</div><input id="ffContactSearch" placeholder="Search staff, manager, sales admin…"><div id="ffChatContacts" class="ffChatContacts"></div></div><div class="card"><div class="cardTitle" id="ffChatTitle">Choose a staff member</div><button class="secondary" id="ffChatOlder" hidden>LOAD OLDER MESSAGES</button><div id="ffChatThread" class="ffChatThread"></div><form class="form" id="ffChatForm"><label>Message<textarea name="body" maxlength="1800" required placeholder="Write your message…"></textarea></label><button class="primary" type="submit">SEND MESSAGE</button></form><div id="ffChatStatus" role="status" class="miniStat"></div></div>`);$('#ffContactSearch').oninput=drawContacts;$('#ffChatForm').onsubmit=async e=>{e.preventDefault();const btn=e.submitter;btn.disabled=true;try{if(!peer)throw Error('Choose a recipient');const text=e.target.elements.body.value;await send(peer,text);e.target.reset();$('#ffChatStatus').textContent='Saved · notification queued';}catch(err){error(err)}finally{btn.disabled=false;}};$('#ffChatOlder').onclick=()=>drawThread(true).catch(error);drawContacts();if(peer)drawThread().catch(error);loadMessages(false).catch(error);}
function drawContacts(){const el=$('#ffChatContacts');if(!el)return;const term=($('#ffContactSearch')?.value||'').toLowerCase();el.innerHTML=people.filter(p=>p.staff_id!==user().id&&[p.full_name,p.role,p.staff_id].join(' ').toLowerCase().includes(term)).map(p=>{const count=messages.filter(m=>m.sender_staff_id===p.staff_id&&m.recipient_staff_id===user().id&&!m.read_at).length;return `<button class="secondary" data-peer="${E(p.staff_id)}">${E(p.full_name)} · ${E(p.role)}${count?' ('+count+')':''}</button>`}).join('');el.querySelectorAll('[data-peer]').forEach(b=>b.onclick=()=>{peer=b.dataset.peer;threadRows=[];drawThread().catch(error)});}
let threadRows=[];
async function drawThread(older=false){const el=$('#ffChatThread');if(!el||!peer)return;const selected=peer;const before=older?threadRows[0]?.created_at:null;let query=sb.from('ffh_live_messages').select('*').or(`and(sender_staff_id.eq.${user().id},recipient_staff_id.eq.${selected}),and(sender_staff_id.eq.${selected},recipient_staff_id.eq.${user().id})`).order('created_at',{ascending:false}).limit(100);if(before)query=query.lt('created_at',before);const {data,error:err}=await query;if(err)throw err;if(peer!==selected||!el.isConnected)return;threadRows=older?[...(data||[]).reverse(),...threadRows]:(data||[]).reverse();$('#ffChatTitle').textContent=people.find(p=>p.staff_id===selected)?.full_name||selected;$('#ffChatOlder').hidden=(data||[]).length<100;const nearBottom=el.scrollHeight-el.scrollTop-el.clientHeight<80;el.innerHTML=threadRows.map(m=>`<div class="ffChatBubble ${m.sender_staff_id===user().id?'ffChatOwn':''}"><p>${E(m.body)}</p><small>${E(new Date(m.created_at).toLocaleString('en-MY'))}${m.sender_staff_id===user().id?' · '+(m.read_at?'Read':'Saved'):''}</small>${m.location_context?'<small>Location follow-up</small>':''}</div>`).join('')||'<div class="empty">Start this conversation.</div>';if(!older&&nearBottom)el.scrollTop=el.scrollHeight;if((data||[]).some(m=>m.recipient_staff_id===user().id&&!m.read_at))await rpc('read',{peer:selected});}
document.addEventListener('visibilitychange',()=>{if(document.hidden)return;if(active()&&!native())startWeb();refresh().catch(console.warn)});
window.addEventListener('ffh-native-status',e=>{if($('#ffDutyStatus'))$('#ffDutyStatus').textContent=String(e.detail?.message||'');});
return{init,shutdown,refresh,gate,attendance:renderAttendance,tracking:()=>renderTracking().catch(error),communication:renderCommunication,canTrack:()=>!!state?.can_track,updateHome,syncNativeIdentity};
};
