window.FFH_CREATE_EARNINGS=function(ctx){'use strict';
const sb=window.FFH_SUPABASE,E=ctx.esc,C=window.FFH_EARNINGS_CORE,$=s=>document.querySelector(s);let state={entries:[],events:[],settings:[],offers:[],approvers:[],can_approve:false},people=[];
const name=id=>people.find(p=>p.staff_id===id)?.full_name||ctx.staff(id)?.name||id;
async function rpc(action,payload={}){const {data,error}=await sb.rpc('ffh_earnings',{action,payload});if(error)throw Error(error.message);return data;}
async function refresh(){if(!ctx.user())return;const before=JSON.stringify(state);state=await rpc('state');const {data,error}=await sb.rpc('ffh_duty',{action:'directory',payload:{}});if(error)throw Error(error.message);people=data||[];
for(const s of state.settings){ctx.db.targets[s.month]??={};ctx.db.targets[s.month][s.staff_id]=+s.actual_target;ctx.db.planningTargets??={};ctx.db.planningTargets[s.month]??={};ctx.db.planningTargets[s.month][s.staff_id]=+s.planning_target;if(s.month===ctx.month()){ctx.db.incomeSetup[s.staff_id]={basic:+s.basic,fuel:+s.fuel,houseRent:+s.house_rent};if(s.staff_id===ctx.user().id&&Object.keys(s.manager_rule||{}).length)ctx.db.managerIncome=s.manager_rule;}}
const legacy=(ctx.db.incentives||[]).filter(x=>!x.cloud);ctx.db.incentives=[...legacy,...state.offers.map(x=>({id:x.id,cloud:true,name:x.title,sr:x.assigned_to,startDate:x.start_date,endDate:x.end_date,groups:x.groups,image:x.poster_url,active:x.active}))];
ctx.db.adjustments=state.entries.filter(x=>x.status==='Approved').map(x=>({id:x.id,sr:x.staff_id,month:x.entry_date.slice(0,7),kind:x.kind,amount:x.amount,reason:x.reason,by:name(x.created_by),date:x.entry_date,cloud:true}));
return before!==JSON.stringify(state);}
const page=(title,html)=>{ctx.shell(ctx.back(title)+html);ctx.bindBack();};
async function targets(){try{await refresh();const id=ctx.currentSr()||ctx.ids()[0]||ctx.user().id;let m=ctx.month();const render=()=>{const s=state.settings.find(x=>x.staff_id===id&&x.month===m)||{},fallback=ctx.db.incomeSetup[id]||{},skuRows=s.sku_targets||[];page('Target & Income Setup',`<div class="card"><form class="form" id="ffIncomeSettings"><label>Staff<select name="staff_id" id="ffTargetStaff">${ctx.ids().map(v=>`<option value="${E(v)}" ${v===id?'selected':''}>${E(name(v))} · ${E(v)}</option>`).join('')}</select></label><label>Month<input name="month" type="month" value="${E(m)}" required></label><div class="two"><label>Actual / Commission Target RM<input name="actual_target" type="number" min="50000" value="${s.actual_target??ctx.target(id,m)}" required></label><label>Planning Target RM<input name="planning_target" type="number" min="0" value="${s.planning_target??ctx.db.planningTargets?.[m]?.[id]??ctx.target(id,m)}" required></label></div><p class="miniStat">Planning does not change commission. Below 80%: 0.5%; 80–100%: 1%; above 100%: 1% of actual target + 2% of excess.</p><div class="two"><label>Basic RM<input name="basic" type="number" min="0" step=".01" value="${s.basic??fallback.basic??ctx.rules.basic??0}"></label><label>Fuel RM<input name="fuel" type="number" min="0" step=".01" value="${s.fuel??fallback.fuel??ctx.rules.fuel??0}"></label></div><label>House Rent RM<input name="house_rent" type="number" min="0" step=".01" value="${s.house_rent??fallback.houseRent??ctx.rules.houseRent??0}"></label><div class="cardTitle">SKU Targets · cartons</div><div id="ffSkuTargetRows"></div><button type="button" class="secondary" id="ffAddSkuTarget">+ SKU TARGET</button><button class="primary">SAVE TO CLOUD</button><div id="ffSettingsStatus" role="status"></div></form></div>`);
const add=x=>{const div=document.createElement('div');div.className='card';div.innerHTML=`<label>SKU<select class="ffTargetSku">${ctx.catalogue().map(v=>`<option value="${E(v)}" ${x?.sku===v?'selected':''}>${E(v)}</option>`).join('')}</select></label><label>Target cartons<input class="ffSkuQty" type="number" min=".01" step=".01" value="${x?.target||''}" required></label><button type="button" class="danger">REMOVE</button>`;div.querySelector('button').onclick=()=>div.remove();$('#ffSkuTargetRows').appendChild(div);};skuRows.forEach(add);$('#ffAddSkuTarget').onclick=()=>add();$('#ffTargetStaff').onchange=e=>{ctx.setView(e.target.value);targets();};$('#ffIncomeSettings [name=month]').onchange=e=>{m=e.target.value;render();};$('#ffIncomeSettings').onsubmit=async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;try{const f=Object.fromEntries(new FormData(e.target));f.sku_targets=[...$('#ffSkuTargetRows').children].map(d=>({sku:d.querySelector('select').value,target:+d.querySelector('input').value}));await rpc('settings',f);await refresh();$('#ffSettingsStatus').textContent='Saved in cloud';}catch(err){$('#ffSettingsStatus').textContent=err.message;}finally{b.disabled=false;}};};render();}catch(err){alert(err.message);}}
function historyHtml(id,m){return state.entries.filter(x=>(!id||x.staff_id===id)&&(!m||x.entry_date.startsWith(m))).map(x=>`<div class="card"><div class="row"><b>${E(x.kind)} · ${x.kind==='Penalty'?'-':'+'}RM ${(+x.amount).toFixed(2)}</b><span>${E(x.status)}</span></div><div class="miniStat">${E(name(x.staff_id))} · ${E(x.staff_id)} · ${E(people.find(p=>p.staff_id===x.staff_id)?.role||'')} · ${E(x.entry_date)}<br>Given by ${E(name(x.created_by))} · ${E(x.created_by)}</div><p>${E(x.reason)}</p>${x.status==='Pending'&&state.can_approve?`<button class="primary ffEntryAction" data-action="approve" data-id="${x.id}">APPROVE</button><button class="secondary ffEntryAction" data-action="reject" data-id="${x.id}">REJECT</button>`:''}${['Pending','Approved'].includes(x.status)&&x.created_by===ctx.user().id?`<button class="secondary ffEntryAction" data-action="reverse" data-id="${x.id}">REFUND / WITHDRAW</button>`:''}<details><summary>Reason & history</summary>${state.events.filter(v=>v.entry_id===x.id).map(v=>`<p class="miniStat">${E(v.action)} by ${E(name(v.actor))} (${E(v.actor)}) · ${E(new Date(v.created_at).toLocaleString('en-MY'))}<br>${E(v.reason)}</p>`).join('')}</details></div>`).join('')||'<div class="empty">No adjustment history.</div>';}
function bindActions(after){document.querySelectorAll('.ffEntryAction').forEach(b=>b.onclick=async()=>{const reason=prompt('Reason (retained permanently in history):');if(!reason?.trim())return;b.disabled=true;try{await rpc(b.dataset.action,{id:b.dataset.id,reason:reason.trim()});await refresh();await after();}catch(err){alert(err.message);b.disabled=false;}});}
function requestHtml(id){return `<details class="card"><summary class="cardTitle">+ INCENTIVE / PENALTY REQUEST</summary><form class="form" id="ffEntryForm"><label>Staff<select name="staff_id">${people.map(p=>`<option value="${E(p.staff_id)}" ${p.staff_id===id?'selected':''}>${E(p.full_name)} · ${E(p.staff_id)}</option>`).join('')}</select></label><label>Date<input name="entry_date" type="date" value="${ctx.today()}" max="${ctx.today()}" required></label><label>Type<select name="kind"><option>Incentive</option><option>Penalty</option></select></label><label>Amount RM<input name="amount" type="number" min=".01" step=".01" required></label><label>Reason<textarea name="reason" maxlength="2000" required></textarea></label><div class="miniStat">Pending until the owner or an authorized approver approves. Refund/withdrawal is restricted to the issuer.</div><button class="primary">SUBMIT FOR APPROVAL</button></form></details>`;}
function bindRequest(after){const f=$('#ffEntryForm');if(f)f.onsubmit=async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;try{await rpc('propose',Object.fromEntries(new FormData(f)));await refresh();await after();}catch(err){alert(err.message);b.disabled=false;}};}
async function ledger(){try{await refresh();ctx.setPage('incomeLedger');let m=ctx.month(),id=ctx.user().id;const render=()=>{page('Incentives & Penalties',`<div class="card"><div class="two"><label>Staff<select id="ffLedgerStaff"><option value="">All staff</option>${people.map(p=>`<option value="${E(p.staff_id)}" ${id===p.staff_id?'selected':''}>${E(p.full_name)} · ${E(p.staff_id)}</option>`).join('')}</select></label><label>Month<input id="ffLedgerMonth" type="month" value="${E(m)}"></label></div><div class="cardTitle">Approved net adjustment: RM ${C.net(state.entries,id,m).toFixed(2)}</div><p class="miniStat">Pending, rejected and refunded entries do not affect income.</p></div>${requestHtml(id)}${ctx.user().id==='M21954'?`<details class="card"><summary class="cardTitle">APPROVAL PERMISSIONS</summary><form id="ffApproverForm" class="form"><label>Staff<select name="staff_id">${people.filter(p=>p.staff_id!=='M21954').map(p=>`<option value="${E(p.staff_id)}">${E(p.full_name)}</option>`).join('')}</select></label><label><input type="checkbox" name="enabled"> Enable approval permission</label><div class="miniStat">Current: ${state.approvers.map(v=>E(name(v))).join(', ')||'Owner only'}</div><button class="secondary">SAVE ACCESS</button></form></details>`:''}${historyHtml(id,m)}`);$('#ffLedgerStaff').onchange=e=>{id=e.target.value;render();};$('#ffLedgerMonth').onchange=e=>{m=e.target.value;render();};bindRequest(ledger);bindActions(ledger);if($('#ffApproverForm'))$('#ffApproverForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);try{await rpc('grant',{staff_id:f.get('staff_id'),enabled:f.has('enabled')});await ledger();}catch(err){alert(err.message);}};};render();}catch(err){alert(err.message);}}
async function saveManager(rule){const id=ctx.user().id,m=ctx.month(),old=state.settings.find(x=>x.staff_id===id&&x.month===m)||{};await rpc('settings',{staff_id:id,month:m,actual_target:old.actual_target||Math.max(50000,ctx.target(id,m)),planning_target:old.planning_target??ctx.target(id,m),basic:old.basic??rule.basic??0,fuel:old.fuel||0,house_rent:old.house_rent||0,sku_targets:old.sku_targets||[],manager_rule:rule});await refresh();}
function appendIncomeHistory(id){const root=document.querySelector('#app main')||document.querySelector('#app .content')||document.querySelector('#app .app');if(!root)return;const box=document.createElement('div');box.innerHTML=`${(state.settings.find(x=>x.staff_id===id&&x.month===ctx.month())?.sku_targets||[]).map(t=>{const got=(ctx.db.sales||[]).filter(v=>v.sr===id&&v.status==='Delivered'&&v.date?.startsWith(ctx.month())&&v.sku===t.sku).reduce((n,v)=>n+(+v.qty||0),0);return `<div class="row"><span>${E(t.sku)}</span><b>${got} / ${t.target} cartons</b></div>`}).join('')}<div class="cardTitle">Adjustment approval & refund history</div>${historyHtml(id,ctx.month())}`;root.appendChild(box);bindActions(ctx.income);}
async function publishOffer(x){await rpc('offer',{title:x.name,assigned_to:x.sr,start_date:x.startDate,end_date:x.endDate,groups:x.groups,poster_url:x.image});await refresh();}
return{refresh,targets,ledger,publishOffer,saveManager,historyHtml,appendIncomeHistory,requestHtml,bindRequest,bindActions,getState:()=>state};};
