const fs=require('node:fs'),assert=require('node:assert/strict'),{JSDOM}=require('/tmp/ffh-qa/node_modules/jsdom');
const mockSource=fs.readFileSync('tests/duty-ui.cjs','utf8').match(/const mock=([\s\S]*?)\n(async|\(async)/)[1].replace(/;\s*$/,'');
const pause=ms=>new Promise(r=>setTimeout(r,ms));
(async()=>{
 const dom=new JSDOM('<div id="app"></div>',{url:'https://mehedialimayon-del.github.io/salesman-performance-app/',runScripts:'outside-only',pretendToBeVisual:true});const w=dom.window;
 w.alert=()=>{};w.confirm=()=>true;w.navigator.geolocation={getCurrentPosition(){},watchPosition(){return 1},clearWatch(){}};w.navigator.serviceWorker={register:async()=>({}),ready:Promise.resolve({})};w.fetch=async()=>({ok:true,json:async()=>[],text:async()=>''});w.eval('('+mockSource+')('+JSON.stringify('M21954')+',true)');
 for(const path of ['data.js','earnings-core.js','earnings.js','duty-core.js','duty.js','ai-learning.js','claim-pdf.js','claims.js','accounts.js','alarms.js','catalogue-bulk.js'])w.eval(fs.readFileSync(path,'utf8'));
 w.eval(fs.readFileSync('app.js','utf8').replace('\n})();','\nwindow.__controls={tasks,notifications,setupPopupMic,setTasks:t=>db.tasks=t,setNotices:t=>db.notifications=t,track:()=>navigate(\'tracking\',()=>ffDuty.tracking())};\n})();'));await pause(180);
 const q=s=>w.document.querySelector(s);
 w.__controls.setTasks(Array.from({length:35},(_,i)=>({id:'test'+i,title:'Task '+i,to:'M21954',created:i<20?'2025-01-01':new Date().toISOString().slice(0,10),status:i<20?'Done':'Open'})));
 w.__controls.tasks();assert.equal(w.document.querySelectorAll('.taskRow').length,15);q('#ffExpandTasks').click();assert.ok(q('.ffFullList'));assert.equal(w.document.querySelectorAll('.taskRow').length,35);q('#ffTaskSearch').value='Task 34';q('#ffTaskSearch').dispatchEvent(new w.Event('input'));assert.equal([...w.document.querySelectorAll('.taskRow')].filter(r=>!r.hidden).length,1);assert.ok(q('#taskForm'),'composer stays available');
 w.__controls.setNotices(Array.from({length:37},(_,i)=>({title:'Notice '+i,body:'Message '+i,read:true,date:'2026-10-07'})));w.__controls.notifications();assert.equal(w.document.querySelectorAll('.ffNoticeRow').length,37);q('#ffExpandInbox').click();assert.ok(q('.ffFullList'));q('#ffNoticeSearch').value='Notice 36';q('#ffNoticeSearch').dispatchEvent(new w.Event('input'));assert.equal([...w.document.querySelectorAll('.ffNoticeRow')].filter(r=>!r.hidden).length,1);
 const originalFrom=w.FFH_SUPABASE.from,popups=[],views=[];const a={id:'gps-fixture',staff_id:'M21954',latitude:3.139,longitude:101.687,check_in:'2026-10-07T04:00:00Z',shift_end:new Date(Date.now()+3600000).toISOString()};const points=[{latitude:3.139,longitude:101.687,accuracy_m:7,speed_mps:0,captured_at:'2026-10-07T04:00:00Z'},{latitude:3.13901,longitude:101.687,accuracy_m:7,speed_mps:0,captured_at:'2026-10-07T04:02:00Z'},{latitude:3.142,longitude:101.69,accuracy_m:8,speed_mps:1,captured_at:'2026-10-07T04:02:30Z'}];
 w.FFH_SUPABASE.from=t=>{if(!['ffh_attendance','ffh_location_points'].includes(t))return originalFrom(t);let single=false,offset=0;const obj={select(){return obj},eq(){return obj},order(){return obj},limit(){return obj},range(start){offset=start;return obj},maybeSingle(){single=true;return obj},then(resolve){return resolve({data:t==='ffh_attendance'?(single?a:[a]):offset?[]:points,error:null})}};return obj};
 const marker=()=>({addTo(){return this},bindTooltip(){return this},bindPopup(html){popups.push(html);return this}});w.L={map:()=>({setView(coords,zoom){views.push({coords,zoom});return this},remove(){},invalidateSize(){}}),tileLayer:()=>({addTo(){}}),layerGroup:()=>({addTo(){return this},clearLayers(){}}),polyline:marker,circleMarker:marker,circle:marker};w.HTMLElement.prototype.scrollIntoView=()=>{};await w.__controls.track();await pause(50);assert.equal(popups.filter(p=>p.includes('Route point')).length,3);assert.ok(popups.every(p=>p.includes('DIRECTIONS')));assert.match(q('#ffStopList').textContent,/2 min/);q('.ffZoomStop').click();assert.equal(views.at(-1).zoom,18);w.FFH_SUPABASE.from=originalFrom;
 w.document.body.innerHTML='<div id="aiPopupChat"></div><input id="aiPopupAsk"><button id="aiPopupMic">mic</button>';let requested;
 w.FieldForceNative={voice:async p=>{requested=p;return {text:'English misrecognition'}},stopVoice:async()=>{}};w.__controls.setupPopupMic();assert.equal(q('.ffVoiceLanguage').value,'bn-BD');await q('#aiPopupMic').onclick();assert.equal(requested.language,'bn-BD');assert.equal(q('#aiPopupAsk').value,'');assert.match(q('#aiPopupChat').textContent,/বাংলা speech/);q('.ffVoiceLanguage').value='en-US';q('.ffVoiceLanguage').dispatchEvent(new w.Event('change'));assert.equal(w.localStorage.getItem('ffh_voice_language'),'en-US');
 dom.window.close();console.log('PASS bounded/full task and notification lists, history expansion, search, Bengali default independent from UI and misrecognition guard');
})().catch(e=>{console.error(e);process.exit(1)});
