/* DOM integration fallback when Chromium cannot be downloaded. Not a visual/device test. */
const fs=require('node:fs'),assert=require('node:assert/strict');const {JSDOM}=require(process.env.FFH_JSDOM_PATH||'/tmp/ffh-qa/node_modules/jsdom');const {webcrypto}=require('node:crypto');
let mockSource=fs.readFileSync(__dirname+'/duty-ui.cjs','utf8').split('const mock=')[1].split('\n(async()=>')[0].replace(/;\s*$/,'');
mockSource=mockSource.replaceAll("id==='M21954'","['M21954','M99001'].includes(id)");
const pause=ms=>new Promise(r=>setTimeout(r,ms));
(async()=>{for(const [id,att] of [['M21954',false],['M22075',false],['M21954',true],['M99001',true],['M99002',false]]){const errors=[];const dom=new JSDOM('<!doctype html><div id="app"></div>',{url:'https://mehedialimayon-del.github.io/salesman-performance-app/',runScripts:'outside-only',pretendToBeVisual:true});const w=dom.window;w.Notification={permission:'granted',requestPermission:async()=>'granted'};w.FFH_ONESIGNAL_STATUS=()=>({permission:'granted',optedIn:true,subscriptionId:'qa-push'});w.FFH_ONESIGNAL_ASK_PERMISSION=async()=>{};w.alert=s=>errors.push('alert: '+s);w.confirm=()=>true;w.console.error=(...s)=>errors.push(s.join(' '));w.console.warn=()=>{};w.addEventListener('error',e=>errors.push(e.message));Object.defineProperty(w.crypto,'randomUUID',{value:()=>webcrypto.randomUUID()});w.navigator.geolocation={getCurrentPosition:cb=>cb({coords:{latitude:3.139,longitude:101.687,accuracy:10},timestamp:Date.now()}),watchPosition:()=>1,clearWatch:()=>{}};w.navigator.serviceWorker={register:async()=>({}),ready:Promise.resolve({showNotification:async()=>{}})};w.L={map:()=>({setView(){return this},remove(){},invalidateSize(){}}),tileLayer:()=>({addTo(){}}),layerGroup:()=>({addTo(){return this},clearLayers(){}})};
w.eval('('+mockSource+')('+JSON.stringify(id)+','+att+')');for(const p of ['data.js','earnings-core.js','earnings.js','duty-core.js','duty.js','ai-learning.js','claim-pdf.js','claims.js','accounts.js','alarms.js','catalogue-bulk.js','app.js'])w.eval(fs.readFileSync(__dirname+'/../'+p,'utf8'));
for(let i=0;i<40&&!w.document.querySelector('[data-page="attendance"]');i++)await pause(25);
const q=s=>w.document.querySelector(s);await pause(30);if(q('#ffhEntryAllow')){q('#ffhEntryAllow').click();await pause(80);}assert.equal(q('#ffhEntryPermissions'),null,'entry permissions accepted');w.document.dispatchEvent(new w.Event('visibilitychange'));await pause(30);assert.equal(q('#ffhEntryPermissions'),null,'permissions must not repeat on app return');assert.ok(q('[data-page="attendance"]'),'attendance home button');const modules=[...w.document.querySelectorAll('.homeGrid .module')].map(b=>b.dataset.page);assert.deepEqual(modules.slice(['M21954','M99001'].includes(id)?-3:-2),['M21954','M99001'].includes(id)?['attendance','tracking','communication']:['attendance','communication']);if(!att){q('[data-page="sales"]').click();await pause(30);assert.ok(q('#ffAttendanceForm'),'sales gated by attendance');assert.equal(q('#saleForm'),null);q('#ffAttendanceForm [name=consent]').checked=true;q('#ffAttendanceForm').dispatchEvent(new w.SubmitEvent('submit',{bubbles:true,cancelable:true,submitter:q('#ffAttendanceForm button')}));await pause(100);}else{q('[data-page="tracking"]').click();await pause(50);assert.ok(q('#ffDutyMap'));}
q('#bh').click();q('[data-page="communication"]').click();await pause(50);q('[data-peer]').click();await pause(30);q('#ffChatForm textarea').value='DOM regression test message';q('#ffChatForm').dispatchEvent(new w.SubmitEvent('submit',{bubbles:true,cancelable:true,submitter:q('#ffChatForm button')}));await pause(100);assert.ok(q('#ffChatThread').textContent.includes('DOM regression test message'));q('#bh').click();await pause(30);if(id==='M21954'){q('[data-page= incentive]'.replace('= ','=')).click();await pause(20);assert.equal(q('.gMode').value,'sales');assert.equal(q('.gSkus').required,false);assert.equal(q('.gSkus').disabled,true);assert.ok(q('.gTarget').parentElement.textContent.includes('Sales RM'));q('#bh').click();q('[data-page="catalogue"]').click();await pause(50);q('#ffBulkCatalogueOpen').click();await pause(100);assert.ok(q('#ffBulkCatalogueForm'),'bulk editor uses real private app context');q('#bh').click();const rpc=w.FFH_SUPABASE.rpc;w.FFH_SUPABASE.rpc=async(name,args)=>name==='ffh_alarms'?{data:{staff:[{id,name:'QA'}],alarms:[]},error:null}:rpc(name,args);await w.ffhAlarmsUI();assert.ok(q('#ffAlarmForm'),'alarm UI uses real private app context');w.FFH_SUPABASE.functions.invoke=async()=>({data:{profiles:[],zones:[]},error:null});await w.ffhAccountsUI();assert.ok(q('#ffCreateAccount'),'account UI uses real private app context');}assert.deepEqual(errors,[]);console.log('PASS DOM integration:',id,'attendance:',att,'home order/gate/chat send/map controls');dom.window.close();}})().catch(e=>{console.error(e);process.exit(1)});
